### ISSUE TITLE
Project maintenance?

### ISSUE THREAD

**Issue by Blond11516** [DefactoSoftware/ex_css_modules#65]
Hi! I'm currently playing around with CSS modules and Phoenix and was wondering if this project is still maintained? There doesn't seem to have been any activity in the last 2 years, but it still has a few dozen recent downloads on hex so I figure someone is still using it at the very least.

There are a few changes I'd like to see before using it myself, so if no one is maintaining this I'll probably fork it.

**Comment by sn3p** [comment]
Hey @Blond11516, thanks for reaching out. This project is still maintained and we use it in our own projects. But there has not been any active development because there was no need nor did we have the time for further improvements.

But we are certainly open for suggestions and welcome improvements. What changes do you have in mind?

**Comment by Blond11516** [comment]
Hi @sn3p! Glad to hear the project is indeed still used!

Here's the list of things I thought could be improved:
1. Add a config option to automatically embed stylesheets in the view. This would allow setting it to false in `config/dev.exs` (or just not set it as false would remain the default) and set it to true in `config/prod.exs`. Then you don't have to worry about it at the call site, but the option remains available on the macro if you really need it. Btw, I'm curious to know how you are handling this in you current projects? Do you have an additional wrapper around ex_css_modules? Do you not embed the stylesheets in prod or always embed them in development?
3. Add a config option to specify your JSON parsing library, like Phoenix does. New Phoenix projects use Jason by default and I think it would be nice to have the option to use it with ex_css_modules too. Also, I'm not sure this is actually a good idea from a maintenance perspective, but it could even feed directly from the configured Phoenix library (either from `Application.get_env` or [`Phoenix.json_library`](https://github.com/phoenixframework/phoenix/blob/92195b9137ff8c7b1cfd4e1922bf53175786a4d3/lib/phoenix.ex?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L87)).
4. The current requirement on `phoenix_html` is too old to be compatible with a brand new Phoenix project. The same is true for `poison`, though by default phoenix doesn't use anymore so I guess that's less of an issue. You can always override it, but it's not ideal.
2. (This one is less important) Add a config option to specify a base directory for the stylesheets. Based on the examples in the readme, you could set it to "assets/css". This reduces the boilerplate for using the library a little bit as well as making it easier to move your whole assets management around, should you need to.
4. (This one is less important) Allow passing stylesheet names without an extension and automatically load any file with a known compatible extension (eg: .css, .sass, .scss, .less) that matches the path. This would allow users to easily change between/support multiple of native CSS, SCSS, LESS, etc. The list of supported extensions could also be configurable, although I don't personally know of any other stylesheet file extensions.
5. (This one is less important) The generated `class` function doesn't work in HEEX templates. It's really not that big of a deal since there is `class_name` which can still be used, but if I were to maintain my own fork I'd probably just remove `class` altogether in favor of `class_name`. Incidentally, that would also remove the requirement on `phoenix_html`. Since this is a breaking change I don't expect you to be on board with this at all, I just thought I'd let you know.

Finally, this isn't strictly related to ex_css_modules but I thought I'd let you know that I just got a new config option merged into `phoenix_live_reload` which makes it do full page reloads when CSS assets are changed instead of the default behaviour of hot-reloading them. You can read all about it in [the PR](https://github.com/phoenixframework/phoenix_live_reload/pull/123) and [the related issue](https://github.com/phoenixframework/phoenix_live_reload/issues/122). It's not released to hex yet but you can pull the dependency from github if you want to use this config.

I can write separate issues if you want to discuss any of these in more detail. I could also get PRs open pretty quickly for changes 1 through 4. 5 would be a bit more work but I could get it done at some point if you think the feature makes sense.

**Comment by Blond11516** [comment]
And btw I wanted to say I took a look around your github and think you've got a few pretty neat little libs and projects in there! Coming from a React background, ex_cell and cell.js are especially interesting (along with ex_css_modules obviously) since proper encapsulation of components is something I find myself missing quite a bit in the Phoenix world :slightly_smiling_face:

**Comment by sn3p** [comment]
Some nice suggestions there, thanks for taking the time 🙂 
I will look into them and go into more detail when I have the time. Of course feel free to commit and open a PR.

**Comment by sn3p** [comment]
> 6. (This one is less important) The generated `class` function doesn't work in HEEX templates. It's really not that big of a deal since there is `class_name` which can still be used, but if I were to maintain my own fork I'd probably just remove `class` altogether in favor of `class_name`. Incidentally, that would also remove the requirement on `phoenix_html`. Since this is a breaking change I don't expect you to be on board with this at all, I just thought I'd let you know.

We noticed this as well when we started using HEEX templates. But like you said removing the `class` helper would be a breaking change. For us as well, because we still depend on it in our EEX and LEEX templates.

**Comment by sn3p** [comment]
Maybe you could split the list into separate issues?

**Comment by Blond11516** [comment]
Done!

1. #68 
2. #69 
3. #70 
4. #71 
5. #72 
6. #73 

Closing this one to keep the discussions in the specific issues.

**Comment by sn3p** [comment]
@Blond11516 are the merged changes enough for you to adopt it in your project?
If there are still things blocking you, please let us know!

**Comment by Blond11516** [comment]
I'd stiil like to tackle https://github.com/DefactoSoftware/ex_css_modules/issues/71 but I've been playing around with different asset pipeline setups that will impact how I end up wanting to implement it. I'll definitely report back once I have a clearer idea of what I actually want to do!

**Comment by sn3p** [comment]
Cool let me know how you end up using it! (or not using it 😆)
